EmployeeApp/Models/Employees/Shift.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;

namespace EmployeeApp.Models.Employees
{
    public class Shift
    {
        public int Id { get; set; }

        public DateTime DateTime { get; set; }

        [Required]
        public byte ShiftTypeId { get; set; }

        public ShiftType ShiftType { get; set; }

        [Required]
        public int DepartmentId { get; set; }

        public Department Department { get; set; }

        public ICollection<Work> Works { get; set; }

        //Constractors

        public Shift()
        {
            Works = new Collection<Work>();
        }

        public Shift(DateTime dateTime, byte shiftTypeId, int departmentId)
        {
            DateTime = dateTime;
            ShiftTypeId = shiftTypeId;
            DepartmentId = departmentId;

            Works = new Collection<Work>();
        }


    }
}

EmployeeApp/Models/Employees/ShiftType.cs
using System.ComponentModel.DataAnnotations;

namespace EmployeeApp.Models.Employees
{
    public class ShiftType
    {
        public byte Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }
    }
}

EmployeeApp/ViewModels/GetWorkDayViewModel.cs
using EmployeeApp.Models.Employees;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EmployeeApp.ViewModels
{
    public class GetWorkDayViewModel
    {
        [DataType(DataType.Date)]
        [FutureDate]
        public DateTime Datetime { get; set; }
        public int DepartmentId { get; set; }
        public IEnumerable<Department> Departments { get; set; }
        public string DepartemtName { get; set; }

        public IEnumerable<Shift> Shifts { get; set; }
        //public ILookup<int,Work> Works { get; set; }



    }
}

EmployeeApp/Controllers/ShiftsController.cs
using EmployeeApp.DAL;
using EmployeeApp.Models.Employees;
using EmployeeApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace EmployeeApp.Controllers
{
    public class ShiftsController : Controller
    {
        private readonly EmployeeAppDbContext _context;

        public ShiftsController()
        {
            _context = new EmployeeAppDbContext();
        }
        

        //get
        public ActionResult NewWork(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var shift = _context.Shifts
                .Include(s => s.Department)
                .Include(s => s.ShiftType)
                .SingleOrDefault(s => s.Id == id);

            if (shift == null)
            {
                return HttpNotFound();
            }

            var employees = _context.Employees
                .Where(e => e.DepartmentId == shift.DepartmentId &&
                !e.Works.Any(w => w.ShiftId == shift.Id && !w.IsCanceled))
                .ToList();

            var workingEmployees = _context.Employees
                .Where(e => e.DepartmentId == shift.DepartmentId &&
                e.Works.Any(w => w.ShiftId == shift.Id && !w.IsCanceled))
                .ToList();

            var viewModel = new AssignShiftEmployeesViewModel
            {
                Shift = shift,
                Employees = employees,
                WorkingEmployees = workingEmployees
            };

            return View(viewModel);
        }

        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewWork(AssignShiftEmployeesViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Employees = _context.Employees
                    .Where(e => e.DepartmentId == viewModel.Shift.DepartmentId)
                    .ToList();
                return View("NewWork", viewModel);
            }

            var employee = viewModel.EmployeeId;
            var shift = viewModel.Shift.Id;

            var exist = _context.Works.Any(w => w.EmployeeID == employee && w.ShiftId == shift);
            var existandiscanceled = _context.Works.Any(w => w.EmployeeID == employee && w.ShiftId == shift && w.IsCanceled);

            if (existandiscanceled)
            {
                var updatedWork = _context.Works.Where(w => w.EmployeeID == employee && w.ShiftId == shift).Single();
                updatedWork.IsCanceled = false;
                _context.SaveChanges();
                 return RedirectToAction("NewWork", viewModel.Shift.Id);
            }
            if (exist)
            {
                return RedirectToAction("");
            }

            var work = new Work(viewModel.EmployeeId, viewModel.Shift.Id);
            _context.Works.Add(work);
            _context.SaveChanges();

            return RedirectToAction("NewWork", viewModel.Shift.Id);
        }

        public ActionResult AddAWorkWeek()
        {
            var viewModel = new WorkDayViewModel
            {
                Departments = _context.Departments.ToList()
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddAWorkWeek(WorkDayViewModel viewModel)
        {
            var shift = _context.Shifts
                .Include(s => s.Department)
                .Include(s => s.ShiftType)
                .Any(s => s.DateTime == viewModel.WorkDate && s.DepartmentId == viewModel.DepartmentId);

            if (!shift)
            {
                for (int j = 0; j < viewModel.NumberOfWorkDays; j++)
                {
                    for (byte i = 1; i <= viewModel.NumbersOfShifts; i++)
                    {
                        var newShift = new Shift(viewModel.WorkDate.AddDays(j), i, viewModel.DepartmentId);
                        _context.Shifts.Add(newShift);
                    }
                }
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            viewModel.Departments = _context.Departments.ToList();
            return View(viewModel);
        }

        public ActionResult Index(DateTime? dateTime, int? departmentId)
        {
            var departments = new GetWorkDayViewModel
            {
                Departments = _context.Departments.ToList()
            };
            if (dateTime == null && departmentId == null)
            {
                return View(departments);
            }
            else
            {
               
                return RedirectToAction("GetWorkDay", new { currentDatetime = dateTime, currnetDpertmentId = departmentId, departmentsToList = departments } );
            }
            

        }



        //Index (works)
        public ActionResult GetWorkDay(DateTime? dateTime, int? departmentId )
        {

            var shifts = _context.Shifts
                                .Include(s => s.Department)
                                .Include(s => s.ShiftType)
                                .Include(s => s.Works)
                                .Include(s => s.Works.Select(w => w.Employee))
                                .Where(s => s.DateTime == dateTime && s.DepartmentId == departmentId)
                                .ToList();

            var ShiftResults = shifts.First();
                               
                                
                      
            var workDay = new GetWorkDayViewModel
            {
                Datetime = ShiftResults.DateTime,
                DepartemtName = ShiftResults.Department.Name,
                Shifts = shifts,
                Departments = _context.Departments.ToList(),
              
            };

            

            return View("GetWorkDay",workDay);
        }

        //Create Get (works)
        public ActionResult Create()
        {
            var viewModel = new ShiftFormViewModel
            {
                Departments = _context.Departments.ToList(),
                ShiftTypes = _context.ShiftTypes.ToList(),
            };

            return View(viewModel);
        }

        //Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ShiftFormViewModel viewModel)
        {
            if ((!ModelState.IsValid || !viewModel.IsValidDayComparedToDate())
                || (ModelState.IsValid && !viewModel.IsValidDayComparedToDate()))
            {
                viewModel.Departments = _context.Departments.ToList();
                viewModel.ShiftTypes = _context.ShiftTypes.ToList();

                return View("Create", viewModel);
            };

            var shift = new Shift(viewModel.GetDateTime(), viewModel.ShiftTypeId, viewModel.DepartmentId);
            _context.Shifts.Add(shift);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

EmployeeApp/Controllers/api/ShiftsController.cs
using EmployeeApp.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace EmployeeApp.Controllers.api
{
    public class ShiftsController : ApiController
    {
        private EmployeeAppDbContext _context;

        public ShiftsController()
        {
            _context = new EmployeeAppDbContext();
        }

        [HttpDelete]
        public IHttpActionResult Cancel(string id)
        {
            string myId = id;
            string[] stringId = myId.Split();

            var employeeId = int.Parse(stringId[1]);
            var shiftId = int.Parse(stringId[0]);

            var work = _context.Works
                .Where(w => w.EmployeeID == employeeId && w.ShiftId == shiftId)
                .Single();
                

            if (work.IsCanceled)
                return NotFound();

            _context.Works.Remove(work);
            _context.SaveChanges();

            return Ok();
        }
    }
}

EmployeeApp/Views/Shifts/AddAWorkDay.cshtml
@model EmployeeApp.ViewModels.WorkDayViewModel
@{
    ViewBag.Title = Model.Heading;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Heading</h2>
@using (Html.BeginForm(Model.Action, "Shifts"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.WorkDate)
        @Html.EditorFor(m => m.WorkDate, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.WorkDate)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.DepartmentId)
        @Html.DropDownListFor(m => m.DepartmentId, new SelectList(Model.Departments, "Id", "Name"), "Select", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.DepartmentId)
    </div>

    <button type="submit" class="btn btn-primary btn-lg">Save</button>
}

EmployeeApp/Views/Shifts/AddAWorkWeek.cshtml
@model EmployeeApp.ViewModels.WorkDayViewModel
@{
    ViewBag.Title = "Custom Schedule";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Custom Schedule</h2>
@using (Html.BeginForm("AddAWorkWeek", "Shifts"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.WorkDate)
        @Html.EditorFor(m => m.WorkDate, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.WorkDate)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.DepartmentId)
        @Html.DropDownListFor(m => m.DepartmentId, new SelectList(Model.Departments, "Id", "Name"), "Select", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.DepartmentId)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.NumberOfWorkDays)
        @Html.EditorFor(m => m.NumberOfWorkDays, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.NumberOfWorkDays)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.NumbersOfShifts)
        @Html.EditorFor(m => m.NumbersOfShifts, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.NumbersOfShifts)
    </div>

    <button type="submit" class="btn btn-primary btn-lg">Save</button>
}

EmployeeApp/Views/Shifts/Create.cshtml
@model EmployeeApp.ViewModels.ShiftFormViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Shifts"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.ShiftId)

    <div class="form-group">
        @Html.LabelFor(m => m.Date)
        @Html.TextBoxFor(m => m.Date, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Date)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.DayOfWeek)
        @Html.EnumDropDownListFor(m => m.DayOfWeek, "Select Day", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.DayOfWeek)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ShiftTypeId)
        @Html.DropDownListFor(m => m.ShiftTypeId, new SelectList(Model.ShiftTypes, "Id", "Name"), "Select", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.ShiftTypeId)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.DepartmentId)
        @Html.DropDownListFor(m => m.DepartmentId, new SelectList(Model.Departments, "Id", "Name"), "Select", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.DepartmentId)
    </div>
    <button type="submit" class="btn btn-primary btn-lg">Save</button>

}

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")

}

EmployeeApp/Views/Shifts/GetWorkDay.cshtml
@model EmployeeApp.ViewModels.GetWorkDayViewModel
@{
    ViewBag.Title = "GetWorkDay";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GetWorkDay</h2>

@using (Html.BeginForm("GetWorkDay", "Shifts"))
{
    @Html.AntiForgeryToken()

    <div class="shift-selector-place">
        <div class="shift-selector shift-datetime-selector">
            <label>Choose Date</label>
            <div class="input-date-shift-selector">@Html.EditorFor(m => m.Datetime, new { @class = "form-control" })</div>
            @Html.ValidationMessageFor(m => m.Datetime)
        </div>

        <div class="shift-selector shift-department-selector">
            <label>Choose Department:</label>
            <div class="input-department-shift-selector">@Html.DropDownListFor(m => m.DepartmentId, new SelectList(Model.Departments, "Id", "Name"), new { @class = "form-control" })</div>
            @Html.ValidationMessageFor(m => m.DepartmentId)
        </div>
        <div class="clearfix"></div>
        <button class="btn btn-primary">Show Shifts</button>
    </div>
    <div class="WorkDay">
        <h2>Shifts Of Department: @Model.DepartemtName</h2>
        <h3>@Model.Datetime.ToString("dddd, dd MMMM yyyy")</h3>
        <table class="table-bordered shifts-table">
            <tr>
                @foreach (var shift in Model.Shifts)
                {
                    <td>
                        <span class="shift-title">@shift.ShiftType.Name</span>
                        <ul class="shift-employees">
                            @foreach (var work in shift.Works)
                            {
                                <li>
                                    <div class="shift-employee-name">@work.Employee.FullName</div>
                                    <div class="shift-actions">
                                        <span class="col-md-6 col-lg-6"><a href="#" class="js-cancel-work" data-employee-id="@work.ShiftId.ToString() @work.Employee.Id.ToString()" data-shift-id="@shift.Id">Cancel</a></span>
                                        <span class="col-md-6 col-lg-6">Assign Projects</span>
                                    </div>
                                </li>

                            }
                        </ul>
                    </td>
                }
            </tr>
        </table>
    </div>
}

@section scripts
{
    <script>
        $(document).ready(function () {
            $(".js-cancel-work").click(function (e) {
                var link = $(e.target);

                bootbox.dialog({
                    title: 'Confirm',
                    message: "Are you sure you want to delete this Employee from this Shift?",
                    buttons: {
                        no: {
                            label: "No",
                            className: 'btn-default',
                            callback: function () {
                                bootbox.hideAll();
                            }
                        },
                        yes: {
                            label: "Yes",
                            className: 'btn-danger',
                            callback: function () {
                                $.ajax({
                                    url: "/api/shifts/" + link.attr("data-employee-id"),
                                    method: "DELETE"
                                })
                                    .done(function () {
                                        link.parents("li").fadeOut(function () {
                                            this.remove();
                                        });
                                    })
                                    .fail(function () {
                                        alert("Something Failed.")
                                    });
                            }
                        }
                    }
                });
            });

        });

    </script>
}

EmployeeApp/Views/Shifts/Index.cshtml
@model EmployeeApp.ViewModels.GetWorkDayViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

@using (Html.BeginForm("GetWorkDay", "Shifts"))
{
    @Html.AntiForgeryToken()

    <div class="shift-selector-place">
        <div class="shift-selector shift-datetime-selector">
            <label>Choose Date</label>
            <div class="input-date-shift-selector">@Html.EditorFor(m => m.Datetime, new { @class = "form-control" })</div>
            @Html.ValidationMessageFor(m => m.Datetime)
        </div>

        <div class="shift-selector shift-department-selector">
            <label>Choose Department:</label>
            <div class="input-department-shift-selector">@Html.DropDownListFor(m => m.DepartmentId, new SelectList(Model.Departments, "Id", "Name"), new { @class = "form-control" })</div>
            @Html.ValidationMessageFor(m => m.DepartmentId)
        </div>
        <div class="clearfix"></div>
        <button class="btn btn-primary">Show Shifts</button>
    </div>


}

EmployeeApp/Views/Shifts/NewWork.cshtml
@model EmployeeApp.ViewModels.AssignShiftEmployeesViewModel

@{
    ViewBag.Title = "AssignEmployeesToShift";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Assign Employees To Shift</h2>

@using (Html.BeginForm("NewWork", "Shifts"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Shift.Id)
    <div>
        @Model.Shift.DateTime
    </div>
    <div>
        @Model.Shift.Department.Name
    </div>
    <div>
        @Model.Shift.ShiftType.Name
    </div> <hr />

    <div class="form-group">
        @Html.LabelFor(m => m.EmployeeId)
        @Html.DropDownListFor(m => m.EmployeeId, new SelectList(Model.Employees, "Id", "FullName"), "Select", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.EmployeeId)
    </div>

    <button class="btn btn-primary">Submit</button>
    <ul>
        @foreach (var employee in Model.WorkingEmployees)
        {
            <li>
                @employee.FullName
            </li>

        }
    </ul>
}